// src/pages/QuizAI.tsx
import { useState } from 'react';
import { motion, type Variants } from 'framer-motion';
import { Sparkles, AlertTriangle, Cpu, Layers, Zap, ArrowRight } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/Card';
import { Button } from '../components/ui/Button';

// PhilNITS FE Syllabus Categories (Mocked subset for UI)
const TOPICS = [
  'Basic Theory of Information',
  'Computer Architecture',
  'Operating Systems',
  'Data Structures & Algorithms',
  'Databases',
  'Networking & Communication',
  'Information Security',
  'Software Engineering & Development',
  'Strategy',
  'Management'
];

const DIFFICULTIES = [
  { id: 'easy', label: 'Easy', icon: Layers, color: 'text-green-500', border: 'border-green-500' },
  { id: 'medium', label: 'Medium', icon: Zap, color: 'text-amber-500', border: 'border-amber-500' },
  { id: 'hard', label: 'Hard', icon: Cpu, color: 'text-red-500', border: 'border-red-500' }
];

// Orchestration Variants
const staggerContainer: Variants = {
  hidden: { opacity: 0 },
  visible: { opacity: 1, transition: { staggerChildren: 0.1 } }
};

const fadeUpVariant: Variants = {
  hidden: { opacity: 0, y: 30 },
  visible: { 
    opacity: 1, 
    y: 0, 
    transition: { type: "spring", stiffness: 250, damping: 24 } 
  }
};

const viewportConfig = { once: true, margin: "-50px" };

export default function QuizAI() {
  const navigate = useNavigate();
  const [selectedTopic, setSelectedTopic] = useState<string>('Networking & Communication');
  const [selectedDifficulty, setSelectedDifficulty] = useState<string>('medium');
  const [questionCount, setQuestionCount] = useState<number>(10);
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = () => {
    setIsGenerating(true);
    // Simulate API call to Gemini Flash
    setTimeout(() => {
      navigate('/quiz/session?mode=ai-generated');
    }, 2000);
  };

  return (
    <div className="flex flex-col gap-8 w-full max-w-4xl mx-auto pb-24 px-1 sm:px-0 pt-4 relative">
      
      {/* Immersive Ambient Glow */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[500px] bg-accent opacity-5 blur-[120px] pointer-events-none -z-10" />

      {/* 1. HEADER */}
      <motion.div 
        initial="hidden"
        animate="visible"
        variants={fadeUpVariant}
        className="flex flex-col items-center justify-center text-center mt-4"
      >
        <div className="w-16 h-16 rounded-2xl bg-accent/10 border border-accent/30 flex items-center justify-center mb-6 shadow-[0_0_30px_rgba(var(--color-accent),0.2)]">
          <Sparkles className="w-8 h-8 text-accent" />
        </div>
        <h1 className="text-4xl sm:text-5xl md:text-6xl font-bold text-text-main font-display tracking-tight leading-none mb-4">
          Forge <span className="text-accent">Sandbox.</span>
        </h1>
        <p className="text-sm sm:text-base text-text-muted max-w-xl leading-relaxed">
          Configure parameters for Gemini 1.5 Flash. The AI will synthesize a completely novel set of practice scenarios based on your exact specifications.
        </p>
      </motion.div>

      {/* 2. DISCLAIMER */}
      <motion.div variants={fadeUpVariant} initial="hidden" animate="visible">
        <div className="bg-amber-500/10 border border-amber-500/30 rounded-xl p-4 sm:p-5 flex gap-4 items-start">
          <AlertTriangle className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" />
          <div>
            <p className="text-sm font-bold text-amber-600 dark:text-amber-400 font-display mb-1">AI-Generated Content Warning</p>
            <p className="text-xs sm:text-sm text-amber-600/80 dark:text-amber-400/80 leading-relaxed">
              These questions are dynamically generated by AI and may not reflect actual PhilNITS FE exam content. Always cross-reference facts with official materials. Stats from this session will be logged separately.
            </p>
          </div>
        </div>
      </motion.div>

      {/* 3. CONFIGURATION PANEL */}
      <motion.div 
        variants={staggerContainer}
        initial="hidden"
        whileInView="visible"
        viewport={viewportConfig}
        className="flex flex-col gap-6"
      >
        <Card className="bg-surface/85 backdrop-blur-md border border-borderline/60 shadow-lg overflow-hidden relative">
          <div className="absolute top-0 left-0 w-1 h-full bg-accent" />
          <CardHeader className="border-b border-borderline/30 pb-4">
            <CardTitle className="font-display font-bold text-xl flex items-center gap-2">
              1. Select Protocol Category
            </CardTitle>
          </CardHeader>
          <CardContent className="p-6">
            <div className="flex flex-wrap gap-3">
              {TOPICS.map((topic) => (
                <button
                  key={topic}
                  onClick={() => setSelectedTopic(topic)}
                  className={`px-4 py-2.5 rounded-lg border text-sm font-body transition-all duration-300 ${
                    selectedTopic === topic 
                      ? 'bg-accent/10 border-accent text-accent shadow-[0_0_15px_rgba(var(--color-accent),0.15)] scale-[1.02]' 
                      : 'bg-surface-2/40 border-borderline/50 text-text-muted hover:border-accent/40 hover:text-text-main'
                  }`}
                >
                  {topic}
                </button>
              ))}
            </div>
          </CardContent>
        </Card>

        <Card className="bg-surface/85 backdrop-blur-md border border-borderline/60 shadow-lg overflow-hidden relative">
          <div className="absolute top-0 left-0 w-1 h-full bg-accent" />
          <CardHeader className="border-b border-borderline/30 pb-4">
            <CardTitle className="font-display font-bold text-xl flex items-center gap-2">
              2. Simulation Parameters
            </CardTitle>
          </CardHeader>
          <CardContent className="p-6 flex flex-col md:flex-row gap-8">
            
            {/* Difficulty Selector */}
            <div className="flex-1">
              <label className="block text-xs font-orbitron tracking-widest text-text-muted uppercase mb-4">Difficulty Matrix</label>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                {DIFFICULTIES.map((diff) => {
                  const Icon = diff.icon;
                  const isSelected = selectedDifficulty === diff.id;
                  return (
                    <button
                      key={diff.id}
                      onClick={() => setSelectedDifficulty(diff.id)}
                      className={`flex flex-col items-center justify-center p-4 rounded-xl border-2 transition-all duration-300 ${
                        isSelected 
                          ? `bg-${diff.color.split('-')[1]}-500/10 ${diff.border} ${diff.color} scale-[1.02]` 
                          : 'bg-surface-2/40 border-borderline/50 text-text-muted hover:border-borderline'
                      }`}
                    >
                      <Icon className="w-6 h-6 mb-2" />
                      <span className="font-bold font-display text-sm">{diff.label}</span>
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Question Count Slider */}
            <div className="md:w-1/3">
              <label className="block text-xs font-orbitron tracking-widest text-text-muted uppercase mb-4">Item Count: <span className="text-accent font-bold text-sm">{questionCount}</span></label>
              <input 
                type="range" 
                min="5" 
                max="15" 
                step="1"
                value={questionCount}
                onChange={(e) => setQuestionCount(Number(e.target.value))}
                className="w-full h-2 bg-surface-2 rounded-lg appearance-none cursor-pointer accent-accent"
              />
              <div className="flex justify-between text-xs text-text-muted mt-2 font-orbitron font-bold">
                <span>5</span>
                <span>15</span>
              </div>
            </div>

          </CardContent>
        </Card>
      </motion.div>

      {/* 4. LAUNCH BUTTON */}
      <motion.div 
        variants={fadeUpVariant}
        initial="hidden"
        whileInView="visible"
        viewport={viewportConfig}
        className="mt-4"
      >
        <Button 
          variant="outline"
          disabled={isGenerating}
          onClick={handleGenerate}
          className={`w-full py-5 text-lg font-orbitron tracking-widest border-accent/50 text-accent hover:bg-accent hover:text-surface transition-all duration-500 relative overflow-hidden group ${isGenerating ? 'opacity-80' : ''}`}
        >
          {/* Animated background fill effect */}
          <div className="absolute inset-0 bg-accent translate-y-full group-hover:translate-y-0 transition-transform duration-500 ease-out -z-10" />
          
          {isGenerating ? (
            <span className="flex items-center gap-3">
              <Sparkles className="w-5 h-5 animate-spin" /> Synthesizing Data...
            </span>
          ) : (
            <span className="flex items-center gap-3">
              Deploy Sandbox <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
            </span>
          )}
        </Button>
      </motion.div>

    </div>
  );
}